/**
 * Build all UI components individually
 *
 * vite-plugin-singlefile doesn't support multiple inputs,
 * so we build each UI separately.
 */

import { execFileSync } from "node:child_process";
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveSplitModules } from "./split-modules.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const split = resolveSplitModules();

// Find all UI directories with index.html
const skip = ["node_modules", "dist", "shared", "components"];
const uis = readdirSync(__dirname).filter((entry) => {
  const entryPath = resolve(__dirname, entry);
  if (!statSync(entryPath).isDirectory()) return false;
  if (entry.startsWith(".") || skip.includes(entry)) return false;

  try {
    statSync(resolve(entryPath, "index.html"));
    return true;
  } catch {
    return false;
  }
});

console.log(`\nBuilding ${uis.length} UIs: ${uis.join(", ")}\n`);
console.log(`Audited local split: ${split.provenance}\n`);

// Ensure dist directory exists
mkdirSync(resolve(__dirname, "dist"), { recursive: true });

// Build each UI
for (const ui of uis) {
  console.log(`Building ${ui}...`);

  try {
    execFileSync(
      "npx",
      ["vite", "build", "--config", "vite.single.config.mjs"],
      {
        cwd: __dirname,
        stdio: "inherit",
        env: {
          ...process.env,
          ...split.environment,
          UI_NAME: ui,
        },
      },
    );
    console.log(`${ui} built successfully\n`);
  } catch {
    console.error(`Failed to build ${ui}\n`);
    process.exit(1);
  }
}

// Publish one generated module per App. The small index keeps literal dynamic
// imports so JSR/npm include every resource while the SysON server only loads
// the HTML requested through resources/read instead of evaluating ~2.4 MB of
// unrelated viewers at startup.
const bundleDir = resolve(__dirname, "bundles");
rmSync(bundleDir, { recursive: true, force: true });
mkdirSync(bundleDir, { recursive: true });
for (const ui of uis) {
  const html = readFileSync(
    resolve(__dirname, "dist", ui, "index.html"),
    "utf8",
  );
  writeFileSync(
    resolve(bundleDir, `${ui}.ts`),
    `// Generated by build-all.mjs. Do not edit manually.\n` +
      `export const UI_HTML = ${JSON.stringify(html)};\n`,
  );
}
const loaders = uis.map((ui) =>
  `  ${JSON.stringify(ui)}: () => import(${
    JSON.stringify(`./bundles/${ui}.ts`)
  })` +
  `.then((module) => module.UI_HTML),`
).join("\n");
writeFileSync(
  resolve(__dirname, "bundles.ts"),
  `// Generated by build-all.mjs. Do not edit manually.\n` +
    `const UI_HTML_LOADERS = {\n${loaders}\n} as const;\n` +
    `export const UI_BUNDLE_NAMES = Object.freeze(Object.keys(UI_HTML_LOADERS));\n` +
    `export async function loadBundledUiHtml(name: keyof typeof UI_HTML_LOADERS): Promise<string> {\n` +
    `  return await UI_HTML_LOADERS[name]();\n` +
    `}\n`,
);
console.log("Generated bundles.ts\n");

console.log(`\nAll UIs built successfully!`);
