/**
 * Build all UI components individually
 *
 * vite-plugin-singlefile doesn't support multiple inputs,
 * so we build each UI separately.
 */

import { execSync } from "node:child_process";
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Find all UI directories with index.html
const skip = ["node_modules", "dist", "shared", "components"];
const uis = readdirSync(__dirname).filter((entry) => {
  const entryPath = resolve(__dirname, entry);
  if (!statSync(entryPath).isDirectory()) return false;
  if (entry.startsWith(".") || skip.includes(entry)) return false;

  try {
    statSync(resolve(entryPath, "index.html"));
    return true;
  } catch {
    return false;
  }
});

console.log(`\nBuilding ${uis.length} UIs: ${uis.join(", ")}\n`);

// Ensure dist directory exists
mkdirSync(resolve(__dirname, "dist"), { recursive: true });

// Build each UI
for (const ui of uis) {
  console.log(`Building ${ui}...`);

  try {
    execSync(`npx vite build --config vite.single.config.mjs`, {
      cwd: __dirname,
      stdio: "inherit",
      env: { ...process.env, UI_NAME: ui },
    });
    console.log(`${ui} built successfully\n`);
  } catch (error) {
    console.error(`Failed to build ${ui}\n`);
    process.exit(1);
  }
}

// Deno only downloads a JSR package's static module graph. Keep the generated
// HTML in a TypeScript module so registry consumers receive the viewer bundles
// without relying on a runtime filesystem scan of unimported assets.
const bundles = Object.fromEntries(
  uis.map((ui) => [
    ui,
    readFileSync(resolve(__dirname, "dist", ui, "index.html"), "utf8"),
  ]),
);
writeFileSync(
  resolve(__dirname, "bundles.ts"),
  `// Generated by build-all.mjs. Do not edit manually.\n` +
    `export const UI_HTML_BY_NAME = ${JSON.stringify(bundles)} as const;\n`,
);
console.log("Generated bundles.ts\n");

console.log(`\nAll UIs built successfully!`);
