// Generated by build-all.mjs. Do not edit manually.
const UI_HTML_LOADERS = {
  "diagram-viewer": () => import("./bundles/diagram-viewer.ts").then((module) => module.UI_HTML),
  "model-explorer-viewer": () => import("./bundles/model-explorer-viewer.ts").then((module) => module.UI_HTML),
  "query-results-viewer": () => import("./bundles/query-results-viewer.ts").then((module) => module.UI_HTML),
  "requirements-trace-viewer": () => import("./bundles/requirements-trace-viewer.ts").then((module) => module.UI_HTML),
  "requirements-viewer": () => import("./bundles/requirements-viewer.ts").then((module) => module.UI_HTML),
  "validation-viewer": () => import("./bundles/validation-viewer.ts").then((module) => module.UI_HTML),
  "value-change-viewer": () => import("./bundles/value-change-viewer.ts").then((module) => module.UI_HTML),
} as const;
export const UI_BUNDLE_NAMES = Object.freeze(Object.keys(UI_HTML_LOADERS));
export async function loadBundledUiHtml(name: keyof typeof UI_HTML_LOADERS): Promise<string> {
  return await UI_HTML_LOADERS[name]();
}
